2025-04-22 03:01:15 - INFO - [logging_config.py:55] - 日志文件已创建: logs/20250422_030115.log
2025-04-22 03:01:15 - INFO - [logging_config.py:55] - 日志文件已创建: logs/20250422_030115.log
2025-04-22 03:01:15 - INFO - [logging_config.py:55] - 日志文件已创建: logs/20250422_030115.log
2025-04-22 03:01:15 - INFO - [logging_config.py:55] - 日志文件已创建: logs/20250422_030115.log
2025-04-22 03:01:15 - INFO - [server_grpc.py:60] - 服务器初始化完成，等待 3 个客户端注册，计划训练 10 轮
2025-04-22 03:01:15 - INFO - [server_grpc.py:344] - 联邦学习安全服务器正在启动，监听端口: 50051
2025-04-22 03:01:15 - INFO - [client_grpc.py:272] - 成功加载客户端数据: /app/data/credit_card_train_normalized.csv, 形状: X=(8000, 26), y=(8000,)
2025-04-22 03:01:15 - INFO - [client_grpc.py:272] - 成功加载客户端数据: /app/data/credit_card_train_normalized.csv, 形状: X=(8000, 26), y=(8000,)
2025-04-22 03:01:15 - INFO - [client_grpc.py:272] - 成功加载客户端数据: /app/data/credit_card_train_normalized.csv, 形状: X=(8000, 26), y=(8000,)
2025-04-22 03:01:15 - DEBUG - [client_grpc.py:81] - 数据集划分完成 - 训练集: (6400, 26), 测试集: (1600, 26)
2025-04-22 03:01:15 - DEBUG - [client_grpc.py:81] - 数据集划分完成 - 训练集: (6400, 26), 测试集: (1600, 26)
2025-04-22 03:01:15 - INFO - [client_grpc.py:88] - 数据初始化完成，训练数据大小: 6400
2025-04-22 03:01:15 - INFO - [client_grpc.py:88] - 数据初始化完成，训练数据大小: 6400
2025-04-22 03:01:15 - DEBUG - [client_grpc.py:81] - 数据集划分完成 - 训练集: (6400, 26), 测试集: (1600, 26)
2025-04-22 03:01:15 - INFO - [client_grpc.py:88] - 数据初始化完成，训练数据大小: 6400
2025-04-22 03:01:15 - INFO - [client_grpc.py:50] - 使用安全通道(SSL/TLS)连接服务器
2025-04-22 03:01:15 - INFO - [client_grpc.py:50] - 使用安全通道(SSL/TLS)连接服务器
2025-04-22 03:01:15 - INFO - [client_grpc.py:71] - 客户端 1 初始化完成，数据集大小: 6400
2025-04-22 03:01:15 - INFO - [client_grpc.py:71] - 客户端 3 初始化完成，数据集大小: 6400
2025-04-22 03:01:15 - INFO - [client_grpc.py:50] - 使用安全通道(SSL/TLS)连接服务器
2025-04-22 03:01:15 - INFO - [client_grpc.py:71] - 客户端 2 初始化完成，数据集大小: 6400
2025-04-22 03:01:15 - ERROR - [client_grpc.py:290] - 训练过程中发生错误: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-04-22T03:01:15.479395775+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate"}"
>
2025-04-22 03:01:15 - ERROR - [client_grpc.py:290] - 训练过程中发生错误: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate", grpc_status:14, created_time:"2025-04-22T03:01:15.47938798+00:00"}"
>
2025-04-22 03:01:15 - ERROR - [client_grpc.py:290] - 训练过程中发生错误: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.2:50051: Peer name server is not in peer certificate", grpc_status:14, created_time:"2025-04-22T03:01:15.479424049+00:00"}"
>
2025-04-22 03:01:15 - INFO - [client_grpc.py:260] - 已关闭gRPC通道
2025-04-22 03:01:15 - INFO - [client_grpc.py:260] - 已关闭gRPC通道
2025-04-22 03:01:15 - INFO - [client_grpc.py:260] - 已关闭gRPC通道
